// Design System Tokens - Color Palette
// Generated by refactor – centralizes color palette and semantic color tokens

/**
 * Base color palette follows a 70/20/10 balance principle.
 * Primary, secondary, and accent colors are defined across 50‑900 scales.
 */
export const colorPalette = {
  primary: {
    50: '#EEF2FF',
    100: '#E0E7FF',
    200: '#C7D2FE',
    300: '#A5B4FC',
    400: '#818CF8',
    500: '#6366F1',
    600: '#4F46E5',
    700: '#4338CA',
    800: '#3730A3',
    900: '#312E81',
  },
  secondary: {
    50: '#FAF5FF',
    100: '#F3E8FF',
    200: '#E9D5FF',
    300: '#D8B4FE',
    400: '#C084FC',
    500: '#8B5CF6',
    600: '#7C3AED',
    700: '#6D28D9',
    800: '#5B21B6',
    900: '#4C1D95',
  },
  accent: {
    400: '#22D3EE',
    500: '#06B6D4',
    600: '#0891B2',
  },
  // Semantic colors
  success: {
    50: '#F0FDF4',
    100: '#DCFCE7',
    200: '#BBF7D0',
    300: '#86EFAC',
    400: '#4ADE80',
    500: '#22C55E',
    600: '#16A34A',
    700: '#15803D',
    800: '#166534',
    900: '#14532D',
  },
  error: {
    50: '#Fef2f2',
    100: '#fee2e2',
    200: '#fecaca',
    300: '#fca5a5',
    400: '#f87171',
    500: '#ef4444',
    600: '#dc2626',
    700: '#b91c1c',
    800: '#991b1b',
    900: '#7f1d1d',
  },
  warning: {
    50: '#fffbeb',
    100: '#fef3c7',
    200: '#fde68a',
    300: '#fcd34d',
    400: '#fbbf24',
    500: '#f59e0b',
    600: '#d97706',
    700: '#b45309',
    800: '#92400e',
    900: '#78350f',
  },
  info: {
    50: '#eff6ff',
    100: '#dbfeaf',
    200: '#bfdbfe',
    300: '#93c5fd',
    400: '#60a5fa',
    500: '#3b82f6',
    600: '#2563eb',
    700: '#1d4ed8',
    800: '#1e40af',
    900: '#1e3a8a',
  },
  neutral: {
    50: '#fafafa',
    100: '#f5f5f5',
    200: '#e5e5e5',
    300: '#d4d4d4',
    400: '#a3a3a3',
    500: '#737373',
    600: '#525252',
    700: '#404040',
    800: '#262626',
    900: '#171717',
    950: '#0a0a0a',
  },
} as const;

/**
 * Typed keys for color palette access.
 */
export type ColorPaletteKey = keyof typeof colorPalette;
export type ColorPalette = typeof colorPalette;

/**
 * Specific named color groups for convenience.
 */
export type PrimaryColor = typeof colorPalette.primary;
export type SecondaryColor = typeof colorPalette.secondary;
export type AccentColor = typeof colorPalette.accent;
export type SemanticColors = typeof colorPalette['success'] & typeof colorPalette['error'] & typeof colorPalette['warning'] & typeof colorPalette['info'];

/**
 * Utility type for all color values (including shades).
 */
export type ColorScale = {
  [k in keyof typeof colorPalette]: typeof colorPalette[k];
};
