// Design System Tokens - Gradients
// Generated by refactor – centralizes gradient definitions used in the UI

/**
 * Gradient definitions used for backgrounds, headers, and decorative elements.
 * Each gradient is referenced via CSS custom properties or via Tailwind utilities.
 */
export const gradients = {
  aurora: {
    1: '#6366F1',
    2: '#A855F7',
    3: '#EC4899',
  },
  nova: {
    1: '#06B6D4',
    2: '#3B82F6',
    3: '#8B5CF6',
  },
  solar: {
    1: '#F59E0B',
    2: '#F97316',
    3: '#EF4444',
  },
  ember: {
    1: '#F43F5E',
    2: '#EC4899',
    3: '#DB2777',
  },
} as const;

/**
 * Typed keys for gradient access.
 */
export type GradientName = keyof typeof gradients;
export type Gradients = typeof gradients;

/**
 * Helper type for gradient stop maps.
 */
export type GradientStopMap = {
  [K in GradientName]: typeof gradients[K];
}[GradientName];