// Design System Tokens - Motion
// Generated by refactor – centralizes animation duration and easing tokens

/**
 * Duration tokens map to standard CSS time values used for transitions and animations.
 * All durations are expressed in milliseconds (or seconds where appropriate).
 */
export const duration = {
  instant: '0ms',
  fast: '150ms',
  normal: '250ms',
  slow: '400ms',
  gradient: '4s',
  gradientFast: '2s',
  slower: '500ms',
} as const;

export const easing = {
  linear: 'linear',
  easeOut: 'cubic-bezier(0.22, 0.61, 0.36, 1)', // SOTA easing
  easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
  easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
  bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
} as const;

/**
 * Keys for duration values.
 */
export type DurationKey = keyof typeof duration;
export type DurationTokens = typeof duration;

/**
 * Keys for easing values.
 */
export type EasingKey = keyof typeof easing;
export type EasingTokens = typeof easing;