// Design System Tokens - Radius
// Generated by refactor – centralizes radius (border‑radius) tokens and types

/**
 * Radius tokens define border‑radius values used across components.
 * Values are expressed as CSS strings that map to design‑system spacing.
 */
export const radius = {
  none: '0',
  sm: '0.375rem', // 6px
  md: '0.5rem',   // 8px
  lg: '0.75rem',  // 12px
  xl: '1rem',     // 16px
  '2xl': '1.5rem',// 24px
  'full': '9999px',
} as const;

/**
 * Keys of the radius object for type‑safe usage.
 */
export type RadiusKey = keyof typeof radius;
export type RadiusTokens = typeof radius;