// Design System Tokens - Spacing
// Generated by refactor – centralizes spacing tokens and types

/**
 * Spacing tokens follow a 4px design system scale.
 * Keys map to CSS custom properties used throughout the UI.
 */
export const spacing = {
  '2xs': '0.25rem', // 4px
  xs: '0.5rem',     // 8px
  sm: '0.75rem',    // 12px
  md: '1rem',       // 16px
  lg: '1.5rem',     // 24px
  xl: '2rem',       // 32px
  '2xl': '3rem',    // 48px
  '3xl': '4rem',    // 64px
  '4xl': '6rem',    // 96px
} as const;

/**
 * Keys of the spacing object, used for type‑safe references.
 */
export type SpacingKey = keyof typeof spacing;
export type SpacingTokens = typeof spacing;